# Generated by Django 5.0.1 on 2026-02-02 17:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('tc_no', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='TC Kimlik No 11 haneli olmalıdır', regex='^\\d{11}$')], verbose_name='TC Kimlik No')),
                ('representative_name', models.CharField(max_length=100, verbose_name='Hane Reisi Adı')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('city', models.CharField(choices=[('konya', 'Konya')], default='konya', max_length=20, verbose_name='İl')),
                ('district', models.CharField(max_length=50, verbose_name='İlçe')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Mahalle')),
                ('address_detail', models.TextField(verbose_name='Adres Detayı')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam')),
                ('location_link', models.URLField(blank=True, verbose_name='Konum Linki')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('active', 'Aktif'), ('inactive', 'Pasif'), ('rejected', 'Reddedildi')], db_index=True, default='pending', max_length=20, verbose_name='Durum')),
                ('distribution_zone', models.CharField(blank=True, help_text='Lojistik planlama için', max_length=50, verbose_name='Dağıtım Bölgesi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('photo_head', models.ImageField(blank=True, upload_to='family_heads/%Y/%m/', verbose_name='Hane Reisi Fotoğrafı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Aile',
                'verbose_name_plural': 'Aileler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('document_type', models.CharField(choices=[('id_card', 'Nüfus Cüzdanı'), ('residence', 'İkamet Belgesi'), ('income', 'Gelir Belgesi'), ('health', 'Sağlık Raporu'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Belge Türü')),
                ('file', models.FileField(upload_to='family_documents/%Y/%m/', verbose_name='Dosya')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='families.family', verbose_name='Aile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Aile Belgesi',
                'verbose_name_plural': 'Aile Belgeleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('relation', models.CharField(choices=[('head', 'Hane Reisi'), ('spouse', 'Eş'), ('child', 'Çocuk'), ('parent', 'Anne/Baba'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Yakınlık')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Yaş')),
                ('is_head', models.BooleanField(default=False, verbose_name='Hane Reisi mi?')),
                ('description', models.CharField(blank=True, help_text='Özel durumlar, hastalıklar vb.', max_length=255, verbose_name='Açıklama')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='families.family', verbose_name='Aile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Aile Bireyi',
                'verbose_name_plural': 'Aile Bireyleri',
                'ordering': ['-is_head', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('image', models.ImageField(upload_to='family_gallery/%Y/%m/', verbose_name='Fotoğraf')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Başlık')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='families.family', verbose_name='Aile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Aile Fotoğrafı',
                'verbose_name_plural': 'Aile Fotoğrafları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50, verbose_name='İlçe')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Mahalle')),
            ],
            options={
                'verbose_name': 'Konum Verisi',
                'verbose_name_plural': 'Konum Verileri',
                'ordering': ['district', 'neighborhood'],
                'unique_together': {('district', 'neighborhood')},
            },
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['status', '-created_at'], name='families_fa_status_7228a4_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['district', 'neighborhood'], name='families_fa_distric_ccabbc_idx'),
        ),
    ]
