# Generated by Django 5.0.1 on 2026-02-02 17:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('name', models.CharField(help_text='Örn: "2024 Yıllık Bütçe"', max_length=200, verbose_name='Bütçe Adı')),
                ('period', models.CharField(choices=[('monthly', 'Aylık'), ('quarterly', 'Çeyrek Yıl'), ('yearly', 'Yıllık')], default='monthly', max_length=20, verbose_name='Dönem')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('target_income', models.DecimalField(decimal_places=2, default=0, help_text='Planlanan gelir (TL)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hedef Gelir')),
                ('target_expense', models.DecimalField(decimal_places=2, default=0, help_text='Planlanan gider (TL)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hedef Gider')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Bütçe',
                'verbose_name_plural': 'Bütçeler',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CashAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Yardım tutarı (TL)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Tutar')),
                ('purpose', models.TextField(help_text='Nakit yardım ne için talep edildi?', verbose_name='Amaç')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('paid', 'Ödendi'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal Edildi')], db_index=True, default='pending', max_length=20, verbose_name='Durum')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('approval_notes', models.TextField(blank=True, help_text='Onay veya red nedeni', verbose_name='Onay Notları')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Nakit'), ('bank_transfer', 'Banka Transferi'), ('check', 'Çek'), ('other', 'Diğer')], help_text='Nasıl ödendi?', max_length=20, verbose_name='Ödeme Yöntemi')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('payment_reference', models.CharField(blank=True, help_text='Dekont no, çek no vb.', max_length=100, verbose_name='Ödeme Referansı')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('account', models.ForeignKey(blank=True, help_text='Hangi hesaptan ödendi?', limit_choices_to={'item_type__in': ['cash', 'account']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_aid_payments', to='inventory.item', verbose_name='Hesap')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cash_aids', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_aids', to='families.family', verbose_name='Aile')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_cash_aids', to=settings.AUTH_USER_MODEL, verbose_name='Ödeyen')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Nakit Yardım',
                'verbose_name_plural': 'Nakit Yardımlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('invoice_type', models.CharField(choices=[('electric', 'Elektrik'), ('water', 'Su'), ('gas', 'Doğalgaz'), ('phone', 'Telefon'), ('internet', 'İnternet'), ('rent', 'Kira'), ('other', 'Diğer')], db_index=True, max_length=20, verbose_name='Fatura Türü')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fatura tutarı (TL)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Tutar')),
                ('institution', models.CharField(help_text='Elektrik şirketi, su idaresi vb.', max_length=100, verbose_name='Kurum')),
                ('donor_name', models.CharField(blank=True, help_text='Donor seçilmemişse buraya yazılır', max_length=100, verbose_name='Bağışçı Adı')),
                ('status', models.CharField(choices=[('available', 'Kullanılabilir'), ('reserved', 'Rezerve Edildi'), ('used', 'Kullanıldı'), ('expired', 'Süresi Doldu')], db_index=True, default='available', max_length=20, verbose_name='Durum')),
                ('reserved_at', models.DateTimeField(blank=True, null=True, verbose_name='Rezerve Tarihi')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Kullanım Tarihi')),
                ('invoice_number', models.CharField(blank=True, help_text='Ödenen fatura numarası', max_length=50, verbose_name='Fatura Numarası')),
                ('expiry_date', models.DateField(blank=True, help_text='Bu tarihten sonra kullanılamaz', null=True, verbose_name='Son Kullanma Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_invoices', to='inventory.donor', verbose_name='Bağışçı')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Rezerve Eden')),
                ('reserved_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_invoices', to='families.family', verbose_name='Rezerve Edilen Aile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_used_invoices', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('used_by_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invoices', to='families.family', verbose_name='Kullanan Aile')),
            ],
            options={
                'verbose_name': 'Askıda Fatura',
                'verbose_name_plural': 'Askıda Faturalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('transaction_type', models.CharField(choices=[('income', 'Gelir'), ('expense', 'Gider')], db_index=True, max_length=10, verbose_name='İşlem Türü')),
                ('amount', models.DecimalField(decimal_places=2, help_text='İşlem tutarı (TL)', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Tutar')),
                ('category', models.CharField(choices=[('donation', 'Bağış'), ('aid', 'Yardım'), ('invoice', 'Fatura'), ('salary', 'Maaş'), ('rent', 'Kira'), ('utility', 'Fatura (Genel)'), ('office', 'Ofis Gideri'), ('vehicle', 'Araç Gideri'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Kategori')),
                ('description', models.TextField(help_text='İşlem detayları', verbose_name='Açıklama')),
                ('receipt', models.FileField(blank=True, help_text='Fatura, makbuz, dekont vb.', upload_to='transactions/%Y/%m/', verbose_name='Belge/Dekont')),
                ('reference_number', models.CharField(blank=True, help_text='Dekont no, fatura no vb.', max_length=50, verbose_name='Referans No')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, help_text='Fiili işlem tarihi', verbose_name='İşlem Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('account', models.ForeignKey(blank=True, help_text='Hangi hesaptan yapıldı?', limit_choices_to={'item_type__in': ['cash', 'account']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.item', verbose_name='Hesap')),
                ('cash_aid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.cashaid', verbose_name='Nakit Yardım')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('pending_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.pendinginvoice', verbose_name='Askıda Fatura')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Mali Hareket',
                'verbose_name_plural': 'Mali Hareketler',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cashaid',
            index=models.Index(fields=['status', '-created_at'], name='finance_cas_status_62e2ca_idx'),
        ),
        migrations.AddIndex(
            model_name='cashaid',
            index=models.Index(fields=['family', '-created_at'], name='finance_cas_family__7e1f03_idx'),
        ),
        migrations.AddIndex(
            model_name='pendinginvoice',
            index=models.Index(fields=['status', 'invoice_type'], name='finance_pen_status_cf1711_idx'),
        ),
        migrations.AddIndex(
            model_name='pendinginvoice',
            index=models.Index(fields=['donor', '-created_at'], name='finance_pen_donor_i_53692c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', '-transaction_date'], name='finance_tra_transac_c69833_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', '-transaction_date'], name='finance_tra_categor_6ebd3a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', '-transaction_date'], name='finance_tra_account_c410d5_idx'),
        ),
    ]
