# Generated by Django 5.0.1 on 2026-02-02 17:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aid', '0001_initial'),
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad / Kurum')),
                ('donor_type', models.CharField(choices=[('individual', 'Bireysel'), ('corporate', 'Kurumsal'), ('foundation', 'Vakıf'), ('association', 'Dernek'), ('government', 'Kamu Kurumu')], default='individual', max_length=20, verbose_name='Bağışçı Türü')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('tax_number', models.CharField(blank=True, help_text='Kurumsal bağışlar için', max_length=20, verbose_name='Vergi Numarası')),
                ('tax_office', models.CharField(blank=True, max_length=100, verbose_name='Vergi Dairesi')),
                ('notes', models.TextField(blank=True, help_text='Bağışçı hakkında özel notlar', verbose_name='Notlar')),
                ('wants_receipt', models.BooleanField(default=False, help_text='Vergi indirimi için belge talep ediyor mu?', verbose_name='Bağış Belgesi İstiyor')),
                ('can_be_contacted', models.BooleanField(default=True, help_text='Tekrar bağış için aranabilir mi?', verbose_name='İletişime Geçilebilir')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Bağışçı',
                'verbose_name_plural': 'Bağışçılar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Listelemelerde sıralama için', verbose_name='Sıralama')),
                ('parent', models.ForeignKey(blank=True, help_text='Alt kategori oluşturmak için', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.itemcategory', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Ürün Kategorisi',
                'verbose_name_plural': 'Ürün Kategorileri',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('name', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('item_type', models.CharField(choices=[('stock', 'Fiziksel Stok'), ('cash', 'Nakit'), ('account', 'Banka Hesabı')], db_index=True, default='stock', max_length=20, verbose_name='Tür')),
                ('unit', models.CharField(choices=[('piece', 'Adet'), ('kg', 'Kilogram'), ('gram', 'Gram'), ('liter', 'Litre'), ('pack', 'Paket'), ('box', 'Kutu'), ('carton', 'Koli'), ('try', 'TL'), ('meter', 'Metre')], default='piece', max_length=10, verbose_name='Birim')),
                ('stock_amount', models.DecimalField(decimal_places=2, default=0, help_text='Mevcut stok miktarı', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stok Miktarı')),
                ('critical_level', models.DecimalField(decimal_places=2, default=0, help_text='Bu seviyenin altında uyarı verilir', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kritik Seviye')),
                ('optimal_level', models.DecimalField(decimal_places=2, default=0, help_text='İdeal stok seviyesi', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Optimal Seviye')),
                ('location', models.CharField(blank=True, help_text='Depo, raf, bölüm numarası', max_length=100, verbose_name='Konum')),
                ('warehouse', models.CharField(blank=True, help_text='Hangi depoda', max_length=100, verbose_name='Depo')),
                ('account_type', models.CharField(blank=True, help_text='Vadesiz, vadeli, kasa vb.', max_length=50, verbose_name='Hesap Türü')),
                ('institution', models.CharField(blank=True, help_text='Banka adı', max_length=100, verbose_name='Kurum')),
                ('iban', models.CharField(blank=True, help_text='TR ile başlar, 26 karakter', max_length=34, verbose_name='IBAN')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Hesap Numarası')),
                ('description', models.TextField(blank=True, help_text='Ürün hakkında detaylı bilgi', verbose_name='Açıklama')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Barkod')),
                ('sku', models.CharField(blank=True, help_text='Stok takip kodu', max_length=50, null=True, unique=True, verbose_name='SKU/Stok Kodu')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Tahmini birim fiyat (TL)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Birim Fiyat')),
                ('enable_low_stock_alert', models.BooleanField(default=True, help_text='Kritik seviyede uyarı verilsin mi?', verbose_name='Düşük Stok Uyarısı')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.itemcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Stok Kalemi',
                'verbose_name_plural': 'Stok Kalemleri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('name', models.CharField(help_text='Örn: "Ocak 2024 Stok Sayımı"', max_length=200, verbose_name='Sayım Adı')),
                ('count_date', models.DateField(verbose_name='Sayım Tarihi')),
                ('status', models.CharField(choices=[('planned', 'Planlandı'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='planned', max_length=20, verbose_name='Durum')),
                ('warehouse', models.CharField(blank=True, help_text='Hangi depo sayıldı', max_length=100, verbose_name='Depo')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Stok Sayımı',
                'verbose_name_plural': 'Stok Sayımları',
                'ordering': ['-count_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=2, help_text='Sistemdeki kayıtlı miktar', max_digits=12, verbose_name='Sistem Miktarı')),
                ('counted_quantity', models.DecimalField(decimal_places=2, help_text='Fiilen sayılan miktar', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sayılan Miktar')),
                ('notes', models.TextField(blank=True, help_text='Fark varsa açıklama', verbose_name='Notlar')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='Ürün')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_items', to='inventory.stockcount', verbose_name='Stok Sayımı')),
            ],
            options={
                'verbose_name': 'Sayım Kalemi',
                'verbose_name_plural': 'Sayım Kalemleri',
                'ordering': ['item__name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('movement_type', models.CharField(choices=[('in', 'Giriş'), ('out', 'Çıkış'), ('adjustment', 'Düzeltme'), ('transfer', 'Transfer')], db_index=True, max_length=20, verbose_name='Hareket Türü')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Miktar')),
                ('donor_name', models.CharField(blank=True, help_text='Donor seçilmemişse buraya yazılır', max_length=100, verbose_name='Bağışçı Adı')),
                ('target_location', models.CharField(blank=True, help_text='Transfer işlemlerinde hedef depo/konum', max_length=100, verbose_name='Hedef Konum')),
                ('description', models.TextField(blank=True, help_text='Hareket nedeni veya detayları', verbose_name='Açıklama')),
                ('reference_number', models.CharField(blank=True, help_text='İrsaliye, fatura no vb.', max_length=50, verbose_name='Referans No')),
                ('receipt', models.FileField(blank=True, help_text='Bağış makbuzu, irsaliye vb.', upload_to='receipts/%Y/%m/', verbose_name='Dekont/Belge')),
                ('stock_before', models.DecimalField(decimal_places=2, default=0, help_text='Otomatik hesaplanır', max_digits=12, verbose_name='İşlem Öncesi Stok')),
                ('stock_after', models.DecimalField(decimal_places=2, default=0, help_text='Otomatik hesaplanır', max_digits=12, verbose_name='İşlem Sonrası Stok')),
                ('aid_request', models.ForeignKey(blank=True, help_text='Hangi talep için çıkış yapıldı', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='aid.aidrequest', verbose_name='Yardım Talebi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('donor', models.ForeignKey(blank=True, help_text='Sadece giriş hareketleri için', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.donor', verbose_name='Bağışçı')),
                ('family', models.ForeignKey(blank=True, help_text='Sadece çıkış hareketleri için', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_stock_items', to='families.family', verbose_name='Aile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.item', verbose_name='Ürün')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Stok Hareketi',
                'verbose_name_plural': 'Stok Hareketleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['donor_type', 'name'], name='inventory_d_donor_t_7bbfb2_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_type', 'name'], name='inventory_i_item_ty_aba939_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'name'], name='inventory_i_categor_66967b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockcountitem',
            unique_together={('stock_count', 'item')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', '-created_at'], name='inventory_s_item_id_384e17_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='inventory_s_movemen_a71f62_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['donor', '-created_at'], name='inventory_s_donor_i_8f0ed6_idx'),
        ),
    ]
