# Generated by Django 5.0.1 on 2026-02-02 17:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AidRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('aid_type', models.CharField(choices=[('cash', 'Nakit Yardım'), ('inkind', 'Ayni Yardım'), ('invoice', 'Fatura Ödemesi'), ('mixed', 'Karma (Nakit + Ayni)')], default='inkind', max_length=20, verbose_name='Yardım Türü')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('prepared', 'Hazırlandı'), ('distributed', 'Dağıtıldı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal Edildi')], db_index=True, default='pending', max_length=20, verbose_name='Durum')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='normal', max_length=20, verbose_name='Öncelik')),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Nakit yardım tutarı (TL)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nakit Miktar')),
                ('request_reason', models.TextField(help_text='Yardım neden talep ediliyor?', verbose_name='Talep Nedeni')),
                ('notes', models.TextField(blank=True, help_text='Ek açıklamalar veya özel notlar', verbose_name='Notlar')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi')),
                ('approval_notes', models.TextField(blank=True, help_text='Onay veya red nedeni', verbose_name='Onay Notları')),
                ('prepared_at', models.DateTimeField(blank=True, null=True, verbose_name='Hazırlık Tarihi')),
                ('distributed_at', models.DateTimeField(blank=True, null=True, verbose_name='Dağıtım Tarihi')),
                ('distribution_photo', models.ImageField(blank=True, help_text='Dağıtım sırasında çekilen fotoğraf', upload_to='distributions/%Y/%m/', verbose_name='Dağıtım Fotoğrafı')),
                ('planned_distribution_date', models.DateField(blank=True, help_text='Yardımın ne zaman dağıtılacağı', null=True, verbose_name='Planlanan Dağıtım Tarihi')),
            ],
            options={
                'verbose_name': 'Yardım Talebi',
                'verbose_name_plural': 'Yardım Talepleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AidDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('name', models.CharField(help_text='Örn: "Ramazan Dağıtımı 2024"', max_length=200, verbose_name='Dağıtım Adı')),
                ('distribution_date', models.DateField(verbose_name='Dağıtım Tarihi')),
                ('distribution_type', models.CharField(choices=[('field', 'Saha Dağıtımı'), ('office', 'Ofisten Teslim'), ('delivery', 'Adrese Teslimat')], default='field', max_length=20, verbose_name='Dağıtım Türü')),
                ('zone', models.CharField(blank=True, help_text='Dağıtım yapılan bölge', max_length=100, verbose_name='Bölge')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlandı mı?')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_distributions', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu Personel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Dağıtım Kaydı',
                'verbose_name_plural': 'Dağıtım Kayıtları',
                'ordering': ['-distribution_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('requested_quantity', models.DecimalField(decimal_places=2, help_text='Ne kadar istendiği', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Talep Edilen Miktar')),
                ('approved_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Ne kadar onaylandığı (talep edilenden farklı olabilir)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Onaylanan Miktar')),
                ('distributed_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Fiilen ne kadar verildiği', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dağıtılan Miktar')),
                ('notes', models.CharField(blank=True, help_text='Özel notlar veya açıklamalar', max_length=255, verbose_name='Notlar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Yardım Kalemi',
                'verbose_name_plural': 'Yardım Kalemleri',
                'ordering': ['aid_request', 'item'],
            },
        ),
    ]
