# Generated by Django 5.0.1 on 2026-02-02 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aid', '0001_initial'),
        ('families', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiditem',
            name='item',
            field=models.ForeignKey(help_text='Stok kaleminden seçilir', on_delete=django.db.models.deletion.PROTECT, to='inventory.item', verbose_name='Ürün'),
        ),
        migrations.AddField(
            model_name='aiditem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_aid_requests', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan'),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='distributed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributed_aid_requests', to=settings.AUTH_USER_MODEL, verbose_name='Dağıtan'),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aid_requests', to='families.family', verbose_name='Aile'),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_aid_requests', to=settings.AUTH_USER_MODEL, verbose_name='Hazırlayan'),
        ),
        migrations.AddField(
            model_name='aidrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen'),
        ),
        migrations.AddField(
            model_name='aiditem',
            name='aid_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='aid.aidrequest', verbose_name='Yardım Talebi'),
        ),
        migrations.AddField(
            model_name='aiddistribution',
            name='aid_requests',
            field=models.ManyToManyField(blank=True, related_name='distributions', to='aid.aidrequest', verbose_name='Yardım Talepleri'),
        ),
        migrations.AddIndex(
            model_name='aidrequest',
            index=models.Index(fields=['status', '-created_at'], name='aid_aidrequ_status_799157_idx'),
        ),
        migrations.AddIndex(
            model_name='aidrequest',
            index=models.Index(fields=['family', '-created_at'], name='aid_aidrequ_family__cfe29f_idx'),
        ),
        migrations.AddIndex(
            model_name='aidrequest',
            index=models.Index(fields=['priority', 'status'], name='aid_aidrequ_priorit_0f58a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aiditem',
            unique_together={('aid_request', 'item')},
        ),
        migrations.AddIndex(
            model_name='aiddistribution',
            index=models.Index(fields=['-distribution_date'], name='aid_aiddist_distrib_5754c4_idx'),
        ),
        migrations.AddIndex(
            model_name='aiddistribution',
            index=models.Index(fields=['zone', '-distribution_date'], name='aid_aiddist_zone_0f8c0b_idx'),
        ),
    ]
